INSERT INTO `trivia` (`id`, `pregunta`, `respuesta`, `opcion_1`, `opcion_2`, `opcion_3`, `categoria`) VALUES
(1, '¿Cuál es la velocidad del sonido', '1.200 kilómetros por hora', '120 kilómetros por hora', '400 kilómetros por hora', '700 kilómetros por hora', '0'),
(2, '¿Cuál es la mejor manera de saber los años de un árbol?', 'Contando sus anillos internos', 'Midiendo el ancho del árbol según su especie', 'Contando la cantidade de ramas y hojas', 'Midiendo su altura', '0'),
(3, '¿De qué está compuesto mayormente el Sol?', 'Gas', 'Lava líquida', 'Hierro derretido', 'Roca', '0'),
(4, 'El Goulash es un tipo de sopa con carne de res ¿de qué país proviene?', 'Hungría', 'República Checa', 'Eslovaquia', 'Irlanda', '2'),
(5, '¿Cuál de los siguientes animales puede correr más rápido?', 'Chita', 'Leopardo', 'Tigre', 'Leon', '0'),
(6, '¿En qué país se encuentra Transilvania?', 'Rumania', 'Bulgaria', 'Croacia', 'Serbia', '1'),
(7, 'La frase -Pienso, luego existo- fue acuñada por: ', 'Descartes', 'Platón', 'Sócrates', 'Hegel', '0'),
(8, '¿Qué significan las siglas en inglés: S.O.S', 'Save Our Souls', 'Save Our Ship', 'Save Our Seal', 'Save Our Saints', '2'),
(9, '¿Cuál fue la primera película en color producida por Disney?', 'Blanca Nieves y los 7 enanos', 'Toy Story', 'La bella durmiente', 'Cenicienta', '2'),
(10, '¿Qué tipo sanguíneo es el menos común en el cuerpo humano?', 'AB negativo', '0 positivo', 'B negativo', 'A positivo', '0'),
(11, '¿Cuál es el peso promedio de un cerebro humano adulto?', '4 kilogramos', '12 kilogramos', '1200 gramos', '400 gramos', '0'),
(12, '¿Cuál es la capital de Pakistán?', 'Islamabad', 'Lahore', 'Karachi', 'Afganistán', '1'),
(13, '¿Cuántos planetas hay en nuestra galaxia?', 'Por lo menos 50 mil millones de planetas', 'Hay 9 planetas', 'Hay 10 planetas', 'Hay 50 millones de planetas', '0'),
(14, '¿De dónde sacan nutrientes las plantas?', 'Desechos de animales', 'Oxígeno', 'Agua', 'De las abejas', '0'),
(15, '¿De cuáles de estos productos Brasil es el mayor productor?', 'Café', 'Arroz', 'Aceite', 'Azúcar', '1'),
(16, '¿Las luneas Titania y Oberon corresponden a qué planeta de nuestro sistema solar?', 'Urano', 'Neptuno', 'Saturno', 'Marte', '0'),
(17, '¿En qué país se originó la tradición del árbol de navidad?', 'Alemania', 'Estados Unidos', 'Irlanda', 'Bélgica', '2'),
(18, '¿Cuál es el país más pequeño en el mundo?', 'El Vaticano', 'Mónaco', 'San Marino', 'Israel', '1'),
(19, '¿Qué vitaminas no se encuentra en un huevo de gallina?', 'Vitamina C', 'Vitamina A', 'Vitamina B', 'Vitamina D', '0'),
(20, '¿Qué fruto seco se utiliza para preparar mazapán?', 'Almendras', 'Castañas de cajú', 'Nueces', 'Maní', '2'),
(21, '¿Cuántos anillos tiene el logo de las olimpiadas?', '5', '6', '7', '8', '3'),
(22, '¿Cuál de estos instrumentos puede producir las notas más alta?', 'Piccolo', 'Corno Francés', 'Flauta Traversa', 'Violín', '3'),
(23, '¿Qué movimiento de expresión artística surgió durante el Imperio Romano de Oriente?', 'Bizantino', 'Helénico', 'Barroco', 'Levantina', '3'),
(24, '¿Quién es conocido por descubrir que los gérmenes producen enfermedades?', 'Louis Pasteur', 'Gregor Mendel', 'Alfred Wallace', 'Charles Darwin', '0'),
(25, '¿Cuán rápido puede correr un avestruz?', '65 kilómetros por hora', '50 kilómetros por hora', '80 kilómetros por hora', '35 kilómetros por hora', '0'),
(26, '¿Cuál de los siguientes lenguajes no es un lenguaje de programación?', 'Panda', 'Ruby', 'Python', 'C++', '2'),
(27, '¿Qué isla caribeña tiene la mayor superficie?', 'Cuba', 'Puerto Rico', 'Jamaica', 'La Española', '1'),
(28, '¿Zulia es una provincia, ¿de qué país?', 'Venezuela', 'Brasil', 'Ecuador', 'Colombia', '1'),
(29, '¿Quién pintó el jardín de las delicias?', 'El Bosco', 'Salvador Dali', 'Francisco Goya', 'Rembrandt', '3'),
(30, 'La sustancia que forma la mayor parte de una célula se llama:', 'Citoplasma', 'Cloroplasma', 'Citofilia', 'Núcleo', '0'),
(31, '¿Qué tipo de galaxia es la vía láctea?', 'Espiral', 'Elíptica', 'Circular', 'Irregular', '0'),
(32, '¿Qué porcentaje de tu visión perderías si quedas ciego de un ojo?', '20%', '50%', '35%', '60%', '0'),
(33, '¿La muerte de quién desató la primera guerra mundial?', 'Archiduque Francisco Fernando', 'Guillermo II', 'James Ussher', 'La reina Victoria', '1'),
(34, '¿Cuál de los siguientes paises fue neutral en la primera guerra mundial?', 'Noruega', 'Alemania', 'Italia', 'Inglaterra', '1'),
(35, '¿Cuál de los siguientes libros fue escrito por Niccolo Machiavelli?', 'El príncipe', 'El arte de la guerra', 'Guerra y Paz', 'En tiempos de guerra', '0'),
(36, '¿Simón Bolivar fue presidente de qué país?', 'Perú', 'Argentina', 'Chile', 'Bolivia', '1'),
(37, '¿Quién fue teórico político y compañero de Karl Marx?', 'Friedrich Engels', 'Friedrich Reich', 'Friedrich Nietzsche', 'Mijaíl Bakunin', '0'),
(38, '¿Dónde se ubicaban las civilizaciones de la Era de Bronce Egeo?', 'Grecia', 'España', 'Algeria', 'Turquía', '1'),
(39, 'Todas las células tienen:', 'Membrana celular', 'Tanto membrana como paredes celulares', 'Paredes celulares', 'Citofilia', '0'),
(40, '¿Qué astrónomo tomó medidas precisas del sistema solar y cientos de estrellas previamente a la invención del telescopio?', 'Tycho Brahe', 'Johannes Kepler', 'Galileo Galilei', 'Claudius Ptolemaeus', '0'),
(41, '¿Cuál de las siguientes no es una teoría científica obsoleta?', 'Selección Natural', 'Lamarckismo', 'Generación espontánea', 'Teoría del Flogisto', '0'),
(42, '¿En qué año se alcanzó la cima del monte Everest?', '1953', '1944', '1961', '1973', '2'),
(43, '¿Quién es el padrino de la música Soul?', 'James Brown', 'Curtis Mayfield', 'Michael Jackson', 'Labi Siffre', '3'),
(44, '¿Cuántas estrellas hay en el sistema solar?', '1', '437.352 contadas hasta ahora', '3', '8', '0'),
(45, 'Según Sigmund Freud, el yo, el super yo y ¿qué otra instancia estructuran el psiquismo?', 'Ello', 'Irracionalidad', 'Inconsciente', 'Líbido', '0'),
(46, '¿A quién pertenece la locución: Veni, vidi, vici?', 'Julio Cesar', 'César Augusto', 'Tiberio', 'Marco Antonio', '1');
